/**
 * @file advanced_expression.js
 * @author graeme.cassels@smartsheet.com
 * @description  
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;
const evaluate        = require('../lib/evaluate');

module.exports = function advanced_expression (app, body) {
  /** @type {String} input The expression to evaluate.  */
  var input = body.payload.moduleParam.input;
  var vars = body.payload.moduleParam.vars;

  if (input !== undefined) {
    /** @type {ModuleResponse} response The Converse AI response to respond with. */
    var response = new ModuleResponse();
    response.setValue({result: evaluate(input, vars)});
    app.send(Status.SUCCESS, response);
  } else {
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' });
  }
};
