/**
 * @file simple_condition.js
 * @author graeme@converse.ai
 * @description Evaluate a simple expression and reroute path accoridingly.
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.ModuleResponse;
const evaluate        = require('../lib/evaluate');

module.exports = function simple_condition (app, body) {
  /** @type {String} input The expression to evaluate.  */
  var input = body.payload.moduleParam.input;

  if (input !== undefined) {
    /** @type {ModuleResponse} response The Converse AI response to respond with. */
    var response = new ModuleResponse();
    response.setExit(evaluate(input) ? 'True' : 'False');
    app.send(Status.SUCCESS, response);
  } else {
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' });
  }
};
